name: Build Tomcat

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out project files
      uses: actions/checkout@v2

    - name: List project files
      run: ls -ltr
